
<?php 
require_once CONTROLLERPATH.'Controller_invoice.php';
if(isset($_POST['mainpage']))
{
    $_SESSION['path']="mainpage";
    header("Location: ".BASEPATH);
}
if(isset($_POST['logout']))
{
    session_destroy();
    header("Location: ".BASEPATH);
}
if(isset($_POST['memberEntry']))
{
    $_SESSION['path']="member";
    header("Location: ".BASEPATH);
}

if(isset($_POST['Prev']) || isset($_POST['Next']))
{
    if(isset($_POST['Prev']))
    {
        $_SESSION['first']=$_SESSION['first']-5;
        $_SESSION['last']=5;
        $count=0;
        $_SESSION['start']=$_SESSION['start']-1;
    }
    elseif (isset($_POST['Next']))
    {
        $_SESSION['first']=$_SESSION['first']+5;
        $_SESSION['last']=5;
        $count=0;
        $_SESSION['start']=$_SESSION['start']+1;
    }
    
}
else
{
    $_SESSION['first']=0;
    $_SESSION['last']=5;
    $count=0;
    $_SESSION['start']=1;
}

    

?>
<div class="members">
    <form method="post" action="" id="show_list" name="show_list">
    <?php 
			if(isset($_POST['updatevalues']))
			{
			   // echo "update value  ".$_POST['updatevalues'];
			    if($_POST['updatevalues']<>"")
			    {
    			       
			        $objs=new Controller_invoice();
			        $objs->delReportsByID($_POST['updatevalues']);
			       
			    }
			}
			?>

    <table>
    <tr>
    	<td><br></td>
    </tr>
    <tr>
    	<td>
    		<table>
    		
			<tr>
				<td align="left">
					Hello <?php echo $_SESSION['username'];?> !
				</td>
			</tr>
			<tr>
				<td>
					<!-- page header starts -->
					<table>
						<tr>
							<td>
								<h1>Invoice</h1>
							</td>
							
							<td>
								<table>
									<tr>
										<td>
											<input type="submit" name="mainpage" value="Close" class="small small-primary small-block small-large">
										</td>
										<td>
											<input type="submit" name="logout" value="Logout" class="small small-primary small-block small-large">
										</td>
									</tr>
										
									
								</table>
							</td>
						</tr>
						<tr>
							
							<td>
								 <select id="shopbyname" class="input1" name="shopbyname" onchange="submitdoc()">
									<option value="">Select Shop</option>
									<option value="">Show ALL</option>
									<?php 
									require_once CONTROLLERPATH.'Controller_Shop.php';
									$objs=new Controller_Shop();
									$Shop_datas=$objs->showAllShop();
									$select="";
									foreach($Shop_datas as $sdata)
									{
									    if(isset($_POST['shopbyname']))
									    {
									        if($sdata['Shop_ID']==$_POST['shopbyname'])
									        {
									            $select="selected";
									        }
									        else 
									        {
									            $select="";
									        }
									    }
									?>
									<option value="<?php echo $sdata['Shop_ID'];?>" <?php echo $select;?>><?php echo $sdata['Shop_Name'];?></option>
									<?php 
									}
									?>
								</select>
								<input type="hidden" id="updatevalues"  name="updatevalues">
							</td>
							
							
						</tr>
					</table>
					<!-- page header ends -->
				</td>
			</tr>
			
			<tr>
				<td>
					<table id="showhidecolumns" border="1">
					<tr>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;Open&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;Shop &nbsp; Name&nbsp;</label></div>
    				</td>
    				
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;Report&nbsp;Name&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;Report Generated ON&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;Amount Due&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;Due Date&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;Report Generated By&nbsp;</label></div>
    				</td>
    				
				</tr>
					<?php 
					
					
					
					
    
					
					$obj=new Controller_invoice();
					if(isset($_POST['shopbyname']))
					{   
					    if($_POST['shopbyname']=="")
					    {
					        $datas=$obj->showAllReports($_SESSION['first'],$_SESSION['last']);
					    }
					    elseif($_POST['shopbyname']<>"")
					    {
					    $id=$_POST['shopbyname'];
					    $datas=$obj->getReportsByID($id,$_SESSION['first'],$_SESSION['last']);
					    $_POST['shopbyname']="";
					    }
					    
					}
					else
					{
					    $datas=$obj->showAllReports($_SESSION['first'],$_SESSION['last']);
					}
					if($datas<>"")
					{    
					foreach($datas as $data)
					{
					    $count=$data['rowcount'];
					?>
				
				<tr>
					<td>
					<table>
						<tr>
							<td><input type="button" onclick="opendoc(<?php echo $data['Report_Id'];?>)" name="View" value="View" class="small small-primary small-block small-large"></td>
							<td><input type="submit" onclick="updatevalue(<?php echo $data['Report_Id'];?>)" name="Delete" value="Delete" class="small small-primary small-block small-large"></td>
						</tr>
					</table>
					
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;<?php echo $data['Shop_Name'];?>&nbsp;</label></div>
    				</td>
    				<td>
    				<div>
    					<label class="description" for="element_1">&nbsp;<?php echo $data['Report_Name'];?>&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;<?php echo $data['Generated_Date'];?>&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;<?php echo $data['Amount_Due'];?>&nbsp;</label></div>
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;<?php echo $data['Due_Date'];?>&nbsp;</label></div>
    					
    				</td>
    				<td>
    					<div>
    					<label class="description" for="element_1">&nbsp;<?php echo $data['Name'];?>&nbsp;</label></div>
    					
    				</td>
				</tr>
				<?php
					}
					}
				?>
				</table>
				
				</td>
			</tr>
			<tr>
    		<td>
    			<?php 
    			
    			$pagecount=ceil($count/5);
    			
    			
    			?>
    			<table>
    				<tr>
    					<td><?php if($_SESSION['first']>0){?><input type="submit"  name="Prev" value="<<"  class="small small-primary small-block small-large"><?php } else { echo "<<";}?></td><td><?php if($pagecount<>0) echo $_SESSION['start']. "  of  ".$pagecount;?></td><td><?php if($_SESSION['start']<$pagecount){?><input type="submit"  name="Next" value=">>" class="small small-primary small-block small-large"><?php } else { echo ">>";}?></td>
    				</tr>
				
		</table>
    	
    	</td>
    </tr>
    </table>
    </td>
    </tr>
    </table>	
  	
    </form>
  </div>